### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by dhowe** [yangsu/eslint-config-p5js#1]
```
$  npm install eslint-config-p5js
$  cd node_modules/eslint-config-p5js/
$  npm install
$  npm run-script generate

> eslint-config-p5js@1.0.1 generate /private/tmp/node_modules/eslint-config-p5js
> browserify node_modules/standardized-audio-context-mock/src/module.js -s 'mock-audio-api' > mock-audio-api.js && node generate.js && rm mock-audio-api.js

ErrorEvent { isTrusted: [Getter] }
script error! TypeError: Cannot set property 'hidden' of undefined
    at p5.createCanvas (about:blank:15966:22)
    at p5.<anonymous> (about:blank:11711:10)
    at new p5 (about:blank:12011:12)
    at /private/tmp/node_modules/eslint-config-p5js/generate.js:40:25
    at invokeEventListeners (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:210:27)
    at EventTargetImpl._dispatch (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:130:9)
    at EventTargetImpl.dispatchEvent (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17)
    at Window.dispatchEvent (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:59)
    at Window.process.nextTick (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/browser/Window.js:409:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7) TypeError: Cannot set property 'hidden' of undefined
    at p5.createCanvas (about:blank:15966:22)
    at p5.<anonymous> (about:blank:11711:10)
    at new p5 (about:blank:12011:12)
    at /private/tmp/node_modules/eslint-config-p5js/generate.js:40:25
    at invokeEventListeners (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:210:27)
    at EventTargetImpl._dispatch (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:130:9)
    at EventTargetImpl.dispatchEvent (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17)
    at Window.dispatchEvent (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:59)
    at Window.process.nextTick (/private/tmp/node_modules/eslint-config-p5js/node_modules/jsdom/lib/jsdom/browser/Window.js:409:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by dhowe** [comment]
also tried:

```
$  git clone git@github.com:yangsu/eslint-config-p5js.git
$  cd eslint-config-p5js
$  npm install
$  npm run-script generate
```

with same error as above

**Comment by dhowe** [comment]
@yangsu ..  is this repo still being developed?

**Comment by yangsu** [comment]
I'll take a look when i have time. You are more than welcome to take a stab at it

**Comment by marksherman** [comment]
Hi all, 
I've made a new eslint plugin that you can use in place of this one. It has all of the globals of p5 hard-coded as an environment. 

https://www.npmjs.com/package/eslint-plugin-p5js

You're welcome to use it, and I look forward to any feedback you have on it!

**Comment by yangsu** [comment]
This shouldn't be a problem now in v1.1.0. Feel free to reopen if needed.
